### PR TITLE
SDK v0.2 (Smart Contract Clients)

### PR DESCRIPTION
**Pull request by jtourkos**
Hi all.

Here's a PR for sharing the new suggested design for the SDK v0.2.
**It is a work in progress and it is _not_ supposed to be merged yet.**

For context, the main SDK components are:

1. The Smart Contract clients.
2. The Subgraph client.
3. The UI example.

This PR addresses the Smart Contract clients - (1).

Feel free to take a look at the code (focus on the `src` folder), but if you prefer a higher-level overview of what's included, here you go:

Following the new "Identity Model", the SDK now provides an [`AddressAppClient`](https://github.com/radicle-dev/drips-js-sdk/blob/feature/update-to-v0.2/src/AddressAppClient.ts) that covers **100% of the [AddressApp smart contract](https://github.com/radicle-dev/drips-contracts/blob/master/src/AddressApp.sol) functions**.

This is were you'll find most of the expected Drips functionality:

image
(scheduled drips, erc20 tokens, are supported)

All public API methods (for all clients) are documented allowing IntelliSense to do its magic:

image

The SDK now throws _typed_ [errors](https://github.com/radicle-dev/drips-js-sdk/blob/feature/update-to-v0.2/src/DripsError.ts).
All `DripsError`s have standard `code`s that the users of the SDK can check against and manage accordingly. The SDK documents when a method could throw an error and what is the type of that error.

The SDK also exposes a "lower level" client for interacting with the [DripsHub smart contract](https://github.com/radicle-dev/drips-contracts/blob/master/src/DripsHub.sol) that you can explicitly create, or access via an `AddressAppClient` instance:

image

This client covers the majority of the `DripsHub` smart contract's _read_ API, although the main usage of the SDK, at this stage, will most probably be done via the `AddressAppClient`.

I'll submit a full PR as soon as the `SubgraphClient` and the UI examples are implemented.

Looking forward to your feedback, and sharing any thoughts, ideas, or concerns you may have!

Thanks!

### CODE REVIEW

**Comment by gh0stwheel** [comment]
Hey @jtourkos -- sorry for the delay on the review and super excited that v0.2 of the SDK is taking shape!

If it's okay, I'm going to share notes in the comments here as I read through the code file by file. With that in mind, one first thing I see is that it looks like the chainIdToNetworkProperiesMap in utils.ts probably should be updated to reflect the new networks for v0.2: https://github.com/radicle-dev/drips-js-sdk/blob/e19f97d0514a0d8aee1baa0626fbf8307522c485/src/utils.ts#L8

Right now v0.2 is only on Goerli, I think we should probably remove all of these other network configs for now, at least until we're on those other networks.

**Comment by gh0stwheel** [comment]
@jtourkos -- I'm sure there's a reason for it, but I don't understand why this second collectAll (ForAddress) method is needed. Using the AddressApp, how can someone ever collect funds for a user that is not the signer?

**Comment by gh0stwheel** [comment]
Okay I think I've gone through all of the code -- looks great overall!

**Review by gh0stwheel — APPROVED** [review]
Looks great

**Comment by jtourkos** [comment]
Thanks, @gh0stwheel for your feedback!

I've made the changes you suggested and regarding [your question](https://github.com/radicle-dev/drips-js-sdk/pull/44#issuecomment-1207293231), as we discussed, there is the possibility of some user B to collect for a user A so that Splits can flow.

I'm continuing with the Subgraph (and UI) changes and will create another PR for those as soon as it's ready.

**Comment by jtourkos** [comment]
Closing this as this PR was to get the initial idea; many things have been added since then.
A full PR on the v2 implementation will follow soon.

**Pull request closed without merging**
