### PR TITLE
Add unit tests for subgraph client

### PR DESCRIPTION
**Pull request by itourkogiorgis**
- Unit tests for subgraph client
- Code coverage reporting
- Relates to: https://github.com/radicle-dev/drips-js-sdk/issues/6
- npm run test:
image
- npm run test:coverage:
image

@gh0stwheel Apologies if I highjacked your issue :) 
After our discussion last week I took the liberty to start working on this one. Next, I'll pick the ones you suggested. Hope it's ok!

### CODE REVIEW

**Comment by gh0stwheel** [comment]
Hey @itourkogiorgis -- this is awesome! You're not hijacking the issue at all, it's great you picked it up :)

One question... I'm trying to run the tests and it's not working. NPM doesn't seem to recognize the "test" command:

>npm ERR! Missing script: "test"
>npm ERR! 
>npm ERR! To see a list of scripts, run:
>npm ERR!   npm run

Do I need to run something first in order to enable tests or install the test framework? I tried `npm i` to reinstall everything, but that didn't solve it...

**Comment by gh0stwheel** [comment]
(`npm run test` is what I tried)

**Comment by itourkogiorgis** [comment]
Hey @gh0stwheel!  Hmm... that's weird :/ . Just tried with a clean clone and seems to work OK. Both `npm test` and `npm run test`.
Could you check in your local copy if the package.json file contains these 3 scripts?
```
"pretest": "tsc",
"test": "env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' mocha -r ts-node/register 'tests/**/*.ts'",
"test:coverage": "nyc npm run test"
```
If it does, well, it's weird :P. 
Let me know and we can have a look together!

**Comment by gh0stwheel** [comment]
Whoops! I was just on the wrong branch in your repo.

Looks good! I've merged your changes into main. Nice work :)

**Pull request merged**
