### PR TITLE
Drips client unit tests

### PR DESCRIPTION
**Pull request by jtourkos**
Hey @gh0stwheel! Another PR for some more tests. 🤓
Please feel free to add more reviewers.

Summary:

- Added unit tests for `DripsClient`.
- Made some minor refactoring in the `DripsClient` code.
- Resolves: https://github.com/radicle-dev/drips-js-sdk/issues/4

image

image

Just a small note. The issue title says "Add Unit/Regression Tests for DripsClient **With Mocks for Blockchain State**" but this wasn't necessary for adding  _unit_ tests.

I believe we should open a new dedicated task/issue for _integration_ tests (in which we'll need to somehow mock a blockchain, or not if we use a testnet - to investigate).
Otherwise, no issue at all, I can try to add the integration tests as part of this PR/task.
Let me know what you think. 😊
Thanks!

### CODE REVIEW

**Comment by gh0stwheel** [comment]
Nice one @jtourkos! Looks great!

I agree with your comment about the Github issue. I'll create a new one related to mocks and integration tests as you recommended.

**Comment by jtourkos** [comment]
@gh0stwheel Sure yes! Let me fix the conflicts and I'll merge.

**Comment by gh0stwheel** [comment]
@jtourkos -- did you mean to reply to the other PR?

**Comment by jtourkos** [comment]
Oops! Yes, I mean the other one.

**Pull request merged**
