### PR TITLE
Add support for querying sub accounts by app and owner

### PR DESCRIPTION
**Pull request by jtourkos**

### CODE REVIEW

**Comment by gh0stwheel** [comment]
Nice work @jtourkos !

One thought here... if I understand the code correctly, there is still not a single function call that an app could make to the SDK that would allow them to query by AssociatedApp *and* by the user's Ethereum address, to retrieve all of the NFT sub-accounts that the user controls, which are associated with the given app.

This strikes me as the function call that most associated apps would actually be most likely to want to make (i.e. when an end-user of that app connects their wallet and then wants to see the accounts they have available associated with that app).

So, something like:

public async getNftSubAccountsByOwner(
		ownerAddress: string,
                 associatedApp: BytesLike): Promise<string[]>
                 
It's definitely possible I'm misunderstanding something here or missing an easy way to do that, but would love to hear what you think! :)

**Comment by jtourkos** [comment]
Hey @gh0stwheel!

You're right. There's no such method. The idea was that the 

```ts
public async getNftSubAccountIds(
	associatedApp: BytesLike,
	userId?: string,
	skip: number = 0,
	first: number = 100
): Promise<string[]>
```

was more generic since it accepts a `userId` instead of an Ethereum address.

But we could definitely add the one you suggest. How you'd imagine constructing the query on the Subgraph?
The Subgraph supports `ownerAddress` in the `NFTSubAccount` entity, but then you would you link to the `associatedApp`s?

**Comment by gh0stwheel** [comment]
Ahh okay... after looking a little deeper into the code I think I see better what's going on here.

I was thinking that the userId parameter in getNftSubAccountIds() would be the userID of the Ethereum Address owning the NFT-based sub-accounts, but after digging into the queries a bit more it seems like it's the userId of the NFT-based sub-account itself.

I think this is not so useful and is actually somewhat confusingly named as it's currently formulated because it means that if you pass a userId parameter to getNftSubAccountIds(), your response would return *at most* just the userId you passed in as a parameter -- not any sub-accounts of it. So I think we should maybe remove this method.

Additionally -- again, unless I'm missing something, which may be possible :) -- I think that this constant should probably be re-named: https://github.com/radicle-dev/drips-js-sdk/blob/7b9843e99a32ae88a3d89ebfc31ecdbbbc28aa52/src/DripsSubgraph/gql.ts#L139

I see "getMetadataHistoryByKeyValueAndOwner" as similarly confusing, because this query is querying based on the userId that the metadata is associated with, not the userId that is the "owner" of that userId sub-account. We've been primarily using the term "owner" to mean a userId that has control over another userId sub-account, rather than to describe the relation between a userId and the metadata associated with it.

....so I would propose renaming getMetadataHistoryByKeyValueAndOwner --> getMetadataHistoryByKeyValueAndUserId.

WDYT?

--

As far as your other question about how to construct this query, I agree that is actually a little tricky. My initial reaction is that for MVP purposes the easiest thing is probably to execute one query on the `NFTSubAccount` type to get all the sub-accounts for the Ethereum address, and then execute one query for each sub-account on the `UserMetadataByKey` type.

Obviously this is kind of clunky and will not scale well, but the truth is that most users will only have a small handful of sub-accounts total for the forseeable future.

The other approach would be for me to modify the `NFTSubAccount` type to add a field of type `User`, and then similarly to add a UserMetadata[] field on the `User` type in the schema, but I'm a little worried about what adding all these object linkages will do in terms of creating load, since it would then mean that any time `NFTSubAccount` gets queried the results are going to pull in and return all of the User details for each userId (and all of their associated linkages).

Anyhow, with that in mind I propose the MVP approach above. 

In general this does make we worry that we're starting to see the complexity limitations of all of the different features and paradigms that we're trying to support and that it might be time to try to make simplifying assumptions in some way....

**Comment by gh0stwheel** [comment]
Really from a practical standpoint, the long-term answer here probably has to be either adding a new field to the existing MetaData types in the subgraph for "ownerUserId", or creating a new metadata-related type in the subgraph that has that.

The thing I don't like about doing that though (similar to what you were saying in your first comment) is that it breaks the whole idea of a "genera" approach to working with user IDs, and starts to build specific assumptions about driver types and userID relations into our base data layer.

**Pull request closed without merging**
