### PR TITLE
Code Review for v0.1 of Drips JS SDK

### PR DESCRIPTION
**Pull request by gh0stwheel**
Hi everyone,

Please take a look at the code in the `full_code_review` branch for the v0.1 version of Drips SDK that I would like to get your feedback on.

The best way to review this may be to review it in the combination with the code from the SDK Examples project, which I will be creating a separate code review for shortly: https://github.com/radicle-dev/drips-sdk-examples/

Take a look at the README from the Examples project for instructions on how to run the web-based example that shows how the SDK can be used.

Thanks!

### CODE REVIEW

**Comment by mattosborn** [comment]
Okay big review dump incoming. I figured I'd keep it all in a single comment as most of this is general and this PR is going to get messy otherwise. I'd also be happy to contribute here and add some commits to cover some of these points.

# General

- Add tests! No coverage currently.
- Consider documentation in code e.g. [https://typedoc.org/](https://typedoc.org/)

# Building and bundling

- Build different module formats for compatibility (cjs and esm)
    - Here’s an example of a starter project you can look at for a template (uses `tsup` for zero config builds)
    - [https://github.com/egoist/ts-lib-starter](https://github.com/egoist/ts-lib-starter)
- Missing `package.json` configuration (see the starter repo above for some examples):
    - `"files"` - the files to be included in the npm package
    - `"module"` - I think this was deprecated or never adopted by may still be used by some tooling so worth including it
    - `"exports"` - new standard allows for different package formats (cjs/esm) [https://nodejs.org/api/packages.html](https://nodejs.org/api/packages.html)
    - `"types"` - should point to bundled type declarations
- Use `peerDependencies` for `@ethersproject/providers` to ensure that users are using a compatible version. Without enforcing this, the risk is that they pass in a `Web3Provider` instance from an incompatible version, resulting in undefined behaviour that could be tricky to debug. `peerDependencies` is designed for this.

# General code

- Add linting and an `.editorconfig` to enforce and standardise code practices (esp things like unused vars, var/let instead of const, etc) [https://typescript-eslint.io/docs/linting/](https://typescript-eslint.io/docs/linting/)
- There are lot of implicit (and some explicit) uses of `any`. Turn on `“noImplicitAny”` (in `tsconfig.json`) & also avoid explicit `any` where at all possible.
- Consider adding typing to the contracts. Good for the type safety and good for library users interacting directly with the contracts we expose. Tooling exists to generate typings automatically, e.g. [https://github.com/dethcrypto/TypeChain](https://github.com/dethcrypto/TypeChain)
- `DripsClient` has a bunch of getX methods returning properties that are already public. I’d suggest either
    - (1) if public readwrite is desired - remove these functions completely and encourage direct usage of the properties or
    - (2) if public readonly is desired, turn the properties into `get` accessors and create private internal properties
- Various functions and consts intended for internal usage only are being exported from the library (from `subgraph.ts` and `utils.ts`).
- Remove unnecessary or unintended `exports`
    - Some exports aren’t used within the library or externally and can be local vars instead. Others are intended for use within the library only and so don’t need to be exported from `index.ts`.
    - Used named exports in `index.ts` instead of wildcard.
- Error handling is currently coarse & catch all. May be worth identifying common errors and handling them properly
- Rename (and reformat) all files in `./src/contracts` to `.json`. The `.ts` format there is a bit of a hacky workaround, but correct configuration and tooling should make json imports possible. `tsup` for example should handle this with no configuration (see the example starter project linked in build section)
- Extract subgraph queries into their own `./queries/<queryname>.gql` files for cleaner separation, editor support, syntax highlighting, etc.
    - Use [[typescript module declarations](https://github.com/evheniy/react-webpack-typescript/blob/main/declarations.d.ts)](https://github.com/evheniy/react-webpack-typescript/blob/main/declarations.d.ts) for typing this
    - And [[register a text loader](https://tsup.egoist.sh/#custom-loader)](https://tsup.egoist.sh/#custom-loader) on that extension for the bundling stage
- It looks like the typings in `global.d.ts` aren’t needed.

# Examples

- Move examples into the main library repo under a subdir `examples/`
- Add a node example
- Tidy up the current svelte example (lots of vanilla js, DOM manipulation, event handling, etc that needs to be refactored)

**Comment by g-tourkogiorgis** [comment]
Hey all! Great points from @mattosborn. Just a few supplementary open questions/suggestions that came up while I was unit testing the `dripsclient.ts`: 

- Would it make sense to encapsulate the `connect()` function’s logic within the constructor?
It seems that connect() contains “internal” logic that *must* run before any other function call.  The user expects (?) when creating a client, `new DripsClient(provider)`, to be immediately in a *valid* state.  
An exception could be thrown in the constructor if the provider is not valid, the signer is not assigned properly, etc.

    This would offer the following benefits:
    - The client users won’t need to know that they must call connect() before any other method, driving them to “proper” use of the client. Someone could easily forget the “second step” of connecting.
        
      ```js
  
      dripsClient = new DripsClient(provider)
      await dripsClient.connect() // <- Here the user needs to know that the client needs to connect.
  
      ```
        
       
    - Exposing only the necessary/minimal API would lead to a better client code encapsulation. There is no need (?) to expose the connect() function.
    - `approveDAIContract()`, `updateUserDrips`,  `updateUserSplits`, would not need to check in their implementation if the signer exists, if it’s connected etc. Since a DripsClient instance has been created, all internal properties should have been properly initialized (_one_ check in the constructor).
    - Side relevant note: It might be a good idea to rename the disconnect method to something like “dispose”, “cleanup”, or similar, if the connect() method will be removed.
- Personal preference: I would explicitly add the return types in every function declaration so that users can quickly identify the types by just looking at a function signature.
- Worth unifying the error message format so that all messages look the same?
- I understand that some methods require the signer to exist (`approveDAIContract`) and some others for the address to exist (`getAllowance`), etc. But since the methods do not accept these dependencies as parameters themselves, but instead, they _retrieve_ them from the provider object passed via the constructor, would it make sense to:
    - Encapsulate these properties (signer, address, networkId) by having public getters and private setters?
    - Perform *all* checks with the `connected` property?
- The `connected` check is based *only* on the networkId property. Shouldn't it check against all the properties (signer, address, networkId)? Extremely minor, but as a convention, I would suggest to name boolean members with a has, is, or similar prefix.
- Some JSdoc comments in the code for the function description, the return types, possible thrown exceptions, etc., might be helpful for the client users.
- When running `npm install` it also builds the project. Where is this configured?
The issue is that because of the build, git treats the generated code as new additions. Should those new files be included in the changes, or should the “contracts” folder be added in .gitignore?
- `signIn()` and `signOut()` functions could be removed since they are not been reused.
- Personal preference: private member names to start with an "_" prefix.
- (Maybe later it might worth investigating a logging library instead of console.logging).

Overall quite straightforward code and easy to understand! Good job! 😊

I'd be happy to implement any of these points if you'd like in a new PR!

**Comment by mattosborn** [comment]
> * Would it make sense to encapsulate the `connect()` function’s logic within the constructor?

The connect function has some async functionality so it can't really be moved into the constructor. The only way to do that would be to emit a `connected` event that lib users could listen for, but this sucks in worse ways imo. Most libs with async initialisation work with a separate async init function like this so devs will be used to it.

> * Personal preference: I would explicitly add the return types in every function declaration so that users can quickly identify the types by just looking at a function signature.

TypeScript infers return types if they aren't explicit anyway, so either way the typedefs will end up looking identical for lib users. Enforcing explicit return types is only really an internal code-styling decision - some developers prefer them to always be there whereas others prefer them only where necessary. In my own projects I usually leave it to be inferred for simple functions, but for functions with multiple return paths, or when you are returning a custom type/interface, sometimes it can make sense to be explicit. I don't really have a strong opinion it though as it's mostly personal preference for readability reasons.

> * I understand that some methods require the signer to exist (`approveDAIContract`) and some others for the address to exist (`getAllowance`), etc. But since the methods do not accept these dependencies as parameters themselves, but instead, they _retrieve_ them from the provider object passed via the constructor, would it make sense to:
>   
>   * Encapsulate these properties (signer, address, networkId) by having public getters and private setters?

This depends on how you want this to look and behave for lib users.
- Do lib users need access to these fields at all?
- Is this for core functionality or just for debugging?
- If this is for core functionality - is exposing this definitely the best way to achieve this?
- Do you want users to have write access? Do you want to enforce this?

Depending on the answer to those questions you can use some combination of accessors, TS `private` or JS `#` to get the result you want. Some examples:
1. Public getter and private setter - `private` is not used in JavaScript and the TypeScript compiler strips these out. Lib consumers using TS should encounter compiler errors when trying to set, but JS consumers would be able to both get and set without error.
1. Public getter to access a regular field. e.g `get signer()` returning `this._signer`, (with no `set` definition). JS lib consumers would still be able to access/modify `this._signer` but it would be clear from the naming that it is intended as private and so would be unlikely to be misused.
1. Public getter to access a private field. Same as above but the `#` operator can be used to create private class fields, so lib consumers would have no way to modify the underlying variable.
1. An _actual_ private field using '#'. If you really want it to be private, and there's no case where access might be useful for debugging, then you could just make it fully private. 

Some info on this: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#which-should-i-use

>   * Perform _all_ checks with the `connected` property?
> * The `connected` check is based _only_ on the networkId property. Shouldn't it check against all the properties (signer, address, networkId)? Extremely minor, but as a convention, I would suggest to name boolean members with a has, is, or similar prefix.

I agree that all those internal checks should use the `connected` property. And regarding what `connected` actually does - this could definitely be improved. I only added this property as part of a quick refactor to create a stable external interface for lib consumers, so I just moved over the check logic that was already being used. I think there's a lot of refactoring that could be done here to improve things, along with the `connect` and `disconnect` functionality.

> * Some JSdoc comments in the code for the function description, the return types, possible thrown exceptions, etc., might be helpful for the client users.

I think @gh0stwheel has added some documentation comments in the latest version.

> * When running `npm install` it also builds the project. Where is this configured?
>   The issue is that because of the build, git treats the generated code as new additions. Should those new files be included in the changes, or should the “contracts” folder be added in .gitignore?

This is probably the `prepare` script: https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts

@gh0stwheel I just took a look at main branch and can see you added the `contracts` directory. It looks like my `.gitignore` changes never made it across when you manually copied my refactor branch over. The `contracts` dir is build output and the whole dir should be added to `.gitignore` and removed from the repo.

**Comment by gh0stwheel** [comment]
@itourkogiorgis and @mattosborn -- thanks for all of the great suggestions and thoughts here! And @mattosborn, good catch on the contracts dir / .gitignore. I fixed that in a branch but somehow it didn't make it over. I've fixed it on main now.

>Would it make sense to encapsulate the connect() function’s logic within the constructor?

@mattosborn makes a good point about the async functionality here. The other thing worth thinking about is that this sort of design is common for these sorts of client libraries, and while @itourkogiorgis makes a good point about the downsides of the current design, I think that in the long-term there are strong potential upsides around allowing a user of the library to call the constructor on the DripsClient separately from calling connect() -- gives them more flexibility in how they separate their own initialization code from the code that will actually initiate the connection. It's also possible in a future version that we might provide more flexibility around disconnecting/reconnecting a given DripsClient, or allow the DripsClient to catch and handle disconnect() messages bubbling up from the underlying Provider (e.g. perhaps the metamask user changes their account or network?). I'm not sure if/whether we want to handle these cases, but I think having the constructor separated from connect() gives us more flexibility there.

>Personal preference: I would explicitly add the return types in every function declaration so that users can quickly identify the types by just looking at a function signature.

@mattosborn makes good points here too. To be honest I was not at all aware of the details that he mentioned regarding TS versus JS. And also based on those details, I feel that this is not an urgent issue.

> I understand that some methods require the signer to exist (approveDAIContract) and some others for the address to exist (getAllowance), etc. 

@mattosborn makes great points here as well. It sounds like there is significant complexity with no obvious path forward. With that said, it would be great to pick the best option out of the 4 that @mattosborn mentioned and add that at some point. I see this as a v0.2 thing. I've created a Github issue:

https://github.com/radicle-dev/drips-js-sdk/issues/9

... @itourkogiorgis, would be great if you can pick this up to work on for v0.2.

>Perform all checks with the connected property?
>The connected check is based only on...

I agree that a full review of connected, and connect/disconnect is needed. It would be great if that review can incorporate even more high-level thinking as well to include some of the considerations I mentioned above, especially related to the details of how connect/disconnect could be triggered by either the DripsClient user or the underlying provider. Let's do this as a part of v0.2. I've created an issue here:

https://github.com/radicle-dev/drips-js-sdk/issues/10

@itourkogiorgis -- this would be a great one for you to pick up and work on in a branch whenever you're ready!

>Some JSdoc comments....

I added TypeDoc as a dev dependency and did a run with it to generate basic documentation in the `docs` dir on the main branch. Check it out when you have a sec and let me know how it looks!

>When running npm install it also builds the project...

@mattosborn -- we had added contracts to .gitignore but it somehow didn't make it into my changes. I've merged this fix into main as well now.

**Comment by jtourkos** [comment]
I believe we can close this one and [this](https://github.com/radicle-dev/drips-js-sdk/pull/2) one @gh0stwheel ?
They are open since the initial version, and we are not going to merge them either way.

**Pull request closed without merging**
